# Server configuration
server.port=8080

# Email-based auto-discovery: set this to the email you sign in with on your phone
app.owner.email=your@email.com
app.discovery.udp.port=45678

jwt.secret=MyVerySecretKey123456789
jwt.expiration=86400000


# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/iot_monitor
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# File storage
app.file.storage-dir=/var/data/iot-monitor/screenshots

# JWT Configuration
app.jwt.secret=your-secret-key-here-should-be-very-long-and-secure
app.jwt.expiration=86400000

#one drive configuration
onedrive.client.id=2b406a28-a974-4e4c-a588-a8b55b5c8867
onedrive.client.secret=_JV8Q~IQ1GaAUlu.~XRvAFvZLSXaSPTDbt0wvHb8P
onedrive.tenant.id=4cfe372a-37a4-44f6-91b2-5faf34253c62
# # DATABASE CONFIG
# spring.datasource.url=jdbc:mysql://localhost:3306/iot_monitor
# spring.datasource.username=root
# spring.datasource.password=YOUR_PASSWORD

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

